# Generated by Django 3.1.7 on 2021-04-12 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='artist',
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
