# Generated by Django 3.1.7 on 2021-09-18 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'verbose_name_plural': 'shipping addresses'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ('-created_at',), 'verbose_name': 'sub category', 'verbose_name_plural': 'sub categories'},
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='deliverymethod',
        ),
    ]
