# Generated by Django 3.1.7 on 2021-12-29 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artwork',
            old_name='is_sold_out',
            new_name='is_active',
        ),
    ]
