# Generated by Django 3.1.7 on 2021-09-25 16:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='artwork',
        ),
        migrations.RemoveField(
            model_name='image',
            name='created_by',
        ),
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'verbose_name_plural': 'shipping addresses'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ('-created_at',), 'verbose_name': 'sub category', 'verbose_name_plural': 'sub categories'},
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='deliverymethod',
        ),
        migrations.AddField(
            model_name='artist',
            name='favorites',
            field=models.ManyToManyField(blank=True, default=None, related_name='favorite_artist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artwork',
            name='favorites',
            field=models.ManyToManyField(blank=True, default=None, related_name='favorite_artwork', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
