# Generated by Django 3.1.7 on 2021-10-30 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='is_carousel',
            field=models.BooleanField(default=False),
        ),
    ]
