# Generated by Django 3.1.7 on 2021-12-17 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0002_auto_20211031_0325'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='province',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
