# Generated by Django 3.1.7 on 2021-09-25 16:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0002_auto_20210925_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='favorites',
            field=models.ManyToManyField(blank=True, default=None, related_name='favorite_artworks', to=settings.AUTH_USER_MODEL),
        ),
    ]
