# Generated by Django 3.1.7 on 2021-12-29 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0003_artwork_is_sold_out'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='is_authenticated',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='is_signed',
        ),
        migrations.AlterField(
            model_name='artwork',
            name='is_sold_out',
            field=models.BooleanField(default=False),
        ),
    ]
