# Generated by Django 3.1.7 on 2021-12-18 01:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0003_myuser_province'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', models.IntegerField(default=0, unique=True)),
                ('price', models.CharField(default='', max_length=350)),
                ('token_Uri', models.CharField(default='', max_length=350)),
                ('content', models.CharField(default='', max_length=350)),
                ('signature', models.CharField(default='', max_length=350)),
            ],
            options={
                'verbose_name': 'signature',
            },
        ),
        migrations.AddField(
            model_name='artwork',
            name='signer_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='TheToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokenID', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.CharField(blank=True, max_length=250, null=True)),
                ('holder', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'NFT',
            },
        ),
        migrations.AddField(
            model_name='artwork',
            name='NFT',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artworks.thetoken'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='signature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artwork_signature', to='artworks.signature'),
        ),
    ]
