# Generated by Django 3.1.7 on 2021-09-26 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0004_auto_20210926_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='phone',
        ),
    ]
