# Generated by Django 3.1.7 on 2021-12-18 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0005_auto_20211218_0549'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Signature',
            new_name='Voucher',
        ),
        migrations.AlterModelOptions(
            name='voucher',
            options={'verbose_name': 'voucher'},
        ),
        migrations.RenameField(
            model_name='artwork',
            old_name='signature',
            new_name='voucher',
        ),
        migrations.AlterField(
            model_name='artwork',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artwork_category', to='artworks.category'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artwork_sub_category', to='artworks.subcategory'),
        ),
    ]
