# Generated by Django 3.1.7 on 2021-04-14 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0006_auto_20210413_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='shippingPrice',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='deliverymethod',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
