# Generated by Django 3.1.7 on 2021-12-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0006_auto_20211218_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheMarketPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Market Place',
            },
        ),
    ]
