# Generated by Django 3.1.7 on 2021-10-02 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0006_myuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='nationality',
            field=models.TextField(blank=True),
        ),
    ]
