# Generated by Django 3.1.7 on 2021-12-18 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0007_themarketplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='store_address',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='myuser',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
