# Generated by Django 3.1.7 on 2021-12-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0007_themarketplace_shipping_variable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themarketplace',
            name='shipping_variable',
            field=models.FloatField(default=1, unique=True),
        ),
    ]
