# Generated by Django 3.1.7 on 2021-12-19 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0008_auto_20211219_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='is_minted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='artwork',
            name='on_market',
            field=models.BooleanField(default=False),
        ),
    ]
