# Generated by Django 3.1.7 on 2021-12-19 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0009_auto_20211219_0621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voucher',
            old_name='token_id',
            new_name='artwork_id',
        ),
    ]
