# Generated by Django 3.1.7 on 2021-12-29 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0009_auto_20211230_0208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paid_at',
        ),
    ]
