# Generated by Django 3.1.7 on 2021-12-19 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0010_auto_20211219_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artwork_signature', to='artworks.voucher'),
        ),
    ]
