# Generated by Django 3.1.7 on 2021-12-19 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0011_auto_20211219_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='title',
            field=models.CharField(default='', max_length=350),
        ),
    ]
