# Generated by Django 3.1.7 on 2021-10-08 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0012_auto_20211008_0729'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'verbose_name': 'artist'},
        ),
    ]
