# Generated by Django 3.1.7 on 2021-12-20 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0012_voucher_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='price_eth',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=100, null=True),
        ),
    ]
