# Generated by Django 3.1.7 on 2021-12-30 03:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0014_auto_20211230_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thetoken',
            name='holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='thetoken',
            name='token_id',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
