# Generated by Django 3.1.7 on 2021-12-30 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0015_auto_20211230_0641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='postalcode',
            new_name='postal_code',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer_shipping', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='province',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
